import type { Sandbox } from "@cloudflare/sandbox";
import type { Context } from "hono";

/**
 * File entry returned by file listing endpoints
 */
export interface FileEntry {
  name: string;
  type: "directory" | "file";
  size: number;
  modified: string;
}

/**
 * Environment bindings for the Cloudflare Worker
 * Actual type comes from worker-configuration.d.ts (generated by wrangler types)
 */
export type AppEnv = {
  Bindings: Env;
};

/**
 * Hono context with environment bindings
 */
export type AppContext = Context<AppEnv>;

/**
 * Result of a sandbox command execution
 */
export interface ExecResult {
  stdout: string;
  stderr: string;
}

/**
 * Session restoration status
 */
export type RestoreStatus =
  | "RESTORED"
  | "NO_R2_DATA"
  | "RESTORE_RSYNC_FAILED"
  | "RESTORE_VERIFY_FAILED";

/**
 * R2 bucket mount error codes
 */
export type MountErrorCode =
  | "MISSING_CREDENTIALS"
  | "INVALID_CONFIG"
  | "MOUNT_FAILED"
  | "VERIFICATION_FAILED";

/**
 * Result of R2 bucket mount operation
 */
export type MountResult =
  | { success: true }
  | { success: false; error: string; code: MountErrorCode };

/**
 * Sandbox instance with session context
 */
export interface SandboxContext {
  sandbox: Sandbox;
  sessionId: string;
  isProduction: boolean;
}
