/**
 * Environment configuration helpers for the sandbox worker.
 * The Env type is auto-generated by wrangler in worker-configuration.d.ts
 */

/**
 * Check if the worker is running in production mode
 */
export function isProduction(env: Env): boolean {
  return env.ENVIRONMENT === "production";
}

/**
 * Get the R2 endpoint URL for the given account
 */
export function getR2Endpoint(env: Env): string {
  return `https://${env.CF_ACCOUNT_ID}.r2.cloudflarestorage.com`;
}

/**
 * R2 bucket configuration
 */
export const R2_CONFIG = {
  bucketName: "claude-sessions",
  mountPath: "/persistent",
} as const;

/**
 * Container server configuration
 */
export const CONTAINER_CONFIG = {
  port: 8080,
  healthPath: "/health",
  startTimeout: 30000,
  entrypoint: "bun /workspace/dist/index.js",
} as const;

/**
 * Sandbox default options
 */
export const SANDBOX_CONFIG = {
  sleepAfter: "1m",
} as const;

/**
 * API configuration for SessionDO persistence
 * These are set via wrangler.jsonc vars or secrets:
 * - API_BASE_URL: Base URL of the API server
 * - INTERNAL_API_TOKEN: Service-to-service auth token
 * - JWT_SECRET: Secret for validating user JWTs (shared with API)
 */
